name: "Hit a webhook"
 
on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: curl -X POST -F 'user=user@acme.com' -F 'pass=hellopixi' https://pixi.andywright.us/andy/api/login
