name: "Hit a webhook"
 
on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST -H 'Content-Type=application/x-www-form-urlencoded' -F 'user=user@acme.com' -F 'pass=hellopixi' https://pixidemo-42c.westeurope.cloudapp.azure.com/api/login
