name: "Hit a webhook"
 
on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST -H 'Content-Type: application/x-www-form-urlencoded' -d '{"user": "user@acme.com", "pass": "hellopixi"}' https://pixi.andywright.us/andy/api/login
