name: Pixi Token

on: push
jobs:

  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.token }}
    steps:
    - id: step1
      run: | 
        echo "::set-output name=token::$(curl -k -d "user=user@acme.com&pass=hellopixi" -X POST https://photo-demo.westeurope.cloudapp.azure.com/andy/api/login | jq -r '.token')"
        
  job2:
    runs-on: ubuntu-latest
    # Wait from the job1 to be completed before starting job2
    needs: job1
    steps:
    - id: step2
      run: |
        echo ${{needs.job1.outputs.output1}}
