on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: 42Crunch Summary
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'

      - name: install python packages
        run: |
          python3 -m pip install --upgrade pip
          pip3 install --user -Iv requests==2.28.1

      - name: execute py script
        run: python3 Audit/getReport.py

      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git add /Audit/report.json
          git commit -m "Updating the repository GitHub audit report.json"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: Audit/report.json
          reactions: eyes